# Metinsel sayıları sayısal değerlere dönüştürme fonksiyonu
def text_to_number(text):
    number_words = {
        "sıfır": 0,
        "bir": 1,
        "iki": 2,
        "üç": 3,
        "sıfır üç":3,
        "03":3,
        "dört": 4,
        "beş": 5,
        "altı": 6,
        "yedi": 7,
        "sekiz": 8,
        "dokuz": 9,
        "on": 10,
        "on bir": 11,
        "on iki": 12,
        "on üç": 13,
        "on dört": 14,
        "on beş": 15,
        "on altı": 16,
        "on yedi": 17,
        "on sekiz": 18,
        "on dokuz": 19,
        "yirmi": 20,
        "yirmi bir": 21,
        "yirmi iki": 22,
        "yirmi üç": 23,
        "yirmi dört": 24,
        "yirmi beş": 25,
        "yirmi altı": 26,
        "yirmi yedi": 27,
        "yirmi sekiz": 28,
        "yirmi dokuz": 29,
        "21": 21,
        "22": 22,
        "23": 23,
        "24": 24,
        "25": 25,
        "26": 26,
        "27": 27,
        "28": 28,
        "29": 29,
        "otuz": 30,
        "kırk": 40,
        "elli": 50,
        "altmış": 60
    }
    return number_words.get(text, text)  # Eğer sayı değilse, metni olduğu gibi döndür